openapi: 3.0.1
info:
  title: APIWorldtime
  description: API Definition of APIWorldtime
  version: 1.0.0
servers:
- url: http://localhost:8290/api
paths:
  /worldtime:
    get:
      parameters:
      - name: city
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
